services:
  - type: worker
    name: slcrp-main-bot
    runtime: python
    region: oregon
    plan: 0.5c-512mb
    branch: main
    autoDeployTrigger: commit
    buildCommand: pip install -r requirements.txt
    startCommand: python run_bots.py
    disk:
      name: vortex-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: VORTEX_BOT_TOKEN
        sync: false
      - key: VORTEX_DATA_DIR
        value: /var/data
      - key: DISCORD_BOT_DATA_DIR
        value: /var/data/indiana-state